### ISSUE TITLE
Do you still maintain this project?

### ISSUE THREAD

**Issue by panoti** [clamarque/angular-movies#8]
I wanna do something
- [x] update angular
- [x] add playlist
- [x] add TV show
- [x] add Popular, top rate movie/tv
- [ ] ...

**Comment by clamarque** [comment]
yes, I maintain this project :). I will update angular to the latest version but I think that add TV show is useless. there are apps like 'tv show time' dit better than my project, so ... You can already add/edit/remove playlist ;).

**Comment by panoti** [comment]
if you don't have any time, I will help you update. Some confuse things, TV show in TMDB include series movies (such as the flash, arrow, ...), I mention TV show as series movies.

**Comment by clamarque** [comment]
oh ! ok. Nice. I glad you to help me. Fork and create pull request with the new features :)
